name: Ticketing Deployment
on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install semantic
        run: |
          npm install semantic-release

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Azure Login
      #   uses: azure/login@v2
      #   id: az-login
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Get Secrets
      #   id: get-secrets
      #   if: steps.az-login.outcome == 'success'
      #   uses: Azure/get-keyvault-secrets@v1
      #   with:
      #     keyvault: ${{ vars.KEYVAULT_NAME }}
      #     secrets: 'DATABRICKS-CLIENT-SECRET, DATABRICKS-CLIENT-ID'

      # - name: Install Databricks cli
      #   id: databricks-cli-install
      #   if: steps.get-secrets.outcome == 'success'
      #   uses: databricks/setup-cli@main

      # - run: databricks bundle deploy
      #   if: steps.databricks-cli-install.outcome == 'success'
      #   working-directory: .
      #   env:
      #     DATABRICKS_CLIENT_SECRET: ${{ steps.get-secrets.outputs['DATABRICKS-CLIENT-SECRET'] }}
      #     DATABRICKS_CLIENT_ID: ${{ steps.get-secrets.outputs['DATABRICKS-CLIENT-ID'] }}
      #     DATABRICKS_BUNDLE_ENV: ${{ vars.ENV_CONTEXT_VAR }}
