name: Ticketing Deployment
on:
  push:
    branches:
      - main
      - dev
# env:
#   CACHE_KEY: node-deps
#   MONGODB_DB_NAME: gha-demo
permissions:
  id-token: write
  contents: read

# env:
#   # Setting an environment variable with the value of a configuration variable
#   ENV_VAR: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Test
        env:
          ENV_VAR: ${{ vars.ENV_CONTEXT_VAR }}
        run: |
          echo "ENV: $ENV_VAR"

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      # - name: Setup cli
      #   uses: databricks/setup-cli@main
      # - run: databricks bundle deploy
      #   working-directory: .
      #   env:
      #     DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      #     DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      #     DATABRICKS_BUNDLE_ENV: ${{ vars.ENV_CONTEXT_VAR }}
